export const backgrounds = {
  background_type_bug: '#8BD674',
  background_type_dark: '#6F6E78',
  background_type_electric: '#F2CB55',
  background_type_fairy: '#EBA8C3',
  background_type_fighting: '#EB4971',
  background_type_fire: '#FFA756',
  background_type_ground: '#F78551',
  background_type_ice: '#91D8DF',
  background_type_normal: '#B5B9C4',
  background_type_poison: '#9F6E97',
  background_type_psychic: '#FF6568',
  background_type_rock: '#D4C294',
  background_type_steel: '#4C91B2',
  background_type_water: '#58ABF6',
};
